title: Minimalistic
logo: /assets/img/headshot.png
email: odinlee.pro@gmail.com
description: Minimalistic is a theme powered by Jekyll.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/odinleepro
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: www.linkedin.com/in/odinlee

navigation:
  - name: Readme
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
