google_analytics: G-Z8WYPTRT2V

title: Odin Lee
logo: /assets/img/headshot.png
email: odinlee.pro@gmail.com
description: Data Scientist in Training | Graduate Student at University of St. Thomas | Skilled in Python, SQL, R, and Tableau.
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/odinleepro
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/odinlee
  - name: Resume
    icon: <i class="fa-solid fa-file"></i>
    link: /assets/file/resume.pdf
