author: Odin Lee
url: "https://odinleepro.github.io"
colorScheme: auto
google_analytics: G-VESKNRH6L2

headshot: /assets/img/headshot.png
title: Odin Lee
location: "St. Paul, Minnesota"
professional_title: "Graduate Data Scientist"
tagline: "Turning complex data into actionable insights"
platforms:
  - name: Resume
    icon: <i class="fa-solid fa-file-user"></i>
    link: /assets/file/resume.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/odinleepro
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/odinlee
  - name: Email
    icon: <i class="fa-solid fa-envelope"></i>
    link: mailto:odinlee.pro@gmail.com
    
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
